#!/bin/bash
# Función llamada por la señal SIGINT configurada con trap
cleanup() {
    echo "Interrumpido. Matando procesos..."
    pkill -P $$  # Mata todos los procesos hijos del script
    exit 1
}
# Capturar SIGINT (Ctrl+C)
trap cleanup SIGINT

./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &
./app-cliente-pesao &




wait

exit 0