/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_rpc.h"

bool_t
xdr_RpcCoord (XDR *xdrs, RpcCoord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_entry (XDR *xdrs, entry *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_RpcCoord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetRes (XDR *xdrs, GetRes *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_RpcCoord (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
