/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_RPC_H_RPCGEN
#define _CLAVES_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct RpcCoord {
	int x;
	int y;
};
typedef struct RpcCoord RpcCoord;

struct entry {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	RpcCoord value3;
};
typedef struct entry entry;

struct GetRes {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	RpcCoord value3;
};
typedef struct GetRes GetRes;

#define CLAVES_PROG 0x31234567
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SET_VALUE 1
extern  int * set_value_1(entry *, CLIENT *);
extern  int * set_value_1_svc(entry *, struct svc_req *);
#define GET_VALUE 2
extern  GetRes * get_value_1(int *, CLIENT *);
extern  GetRes * get_value_1_svc(int *, struct svc_req *);
#define DELETE_KEY 3
extern  int * delete_key_1(int *, CLIENT *);
extern  int * delete_key_1_svc(int *, struct svc_req *);
#define MODIFY_VALUE 4
extern  int * modify_value_1(entry *, CLIENT *);
extern  int * modify_value_1_svc(entry *, struct svc_req *);
#define EXIST 5
extern  int * exist_1(int *, CLIENT *);
extern  int * exist_1_svc(int *, struct svc_req *);
#define INIT_SERVICE 6
extern  int * init_service_1(void *, CLIENT *);
extern  int * init_service_1_svc(void *, struct svc_req *);
#define DESTROY_SERVICE 7
extern  int * destroy_service_1(void *, CLIENT *);
extern  int * destroy_service_1_svc(void *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SET_VALUE 1
extern  int * set_value_1();
extern  int * set_value_1_svc();
#define GET_VALUE 2
extern  GetRes * get_value_1();
extern  GetRes * get_value_1_svc();
#define DELETE_KEY 3
extern  int * delete_key_1();
extern  int * delete_key_1_svc();
#define MODIFY_VALUE 4
extern  int * modify_value_1();
extern  int * modify_value_1_svc();
#define EXIST 5
extern  int * exist_1();
extern  int * exist_1_svc();
#define INIT_SERVICE 6
extern  int * init_service_1();
extern  int * init_service_1_svc();
#define DESTROY_SERVICE 7
extern  int * destroy_service_1();
extern  int * destroy_service_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_RpcCoord (XDR *, RpcCoord*);
extern  bool_t xdr_entry (XDR *, entry*);
extern  bool_t xdr_GetRes (XDR *, GetRes*);

#else /* K&R C */
extern bool_t xdr_RpcCoord ();
extern bool_t xdr_entry ();
extern bool_t xdr_GetRes ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_RPC_H_RPCGEN */
